default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: yammer_board_development

test:
  <<: *default
  database: yammer_board_test

production:
  <<: *default
  database: yammer_board_production
